### ISSUE TITLE
Issues running py.test and make_index.py steps from Contributor Guide

### ISSUE THREAD

**Issue by MaxGhenis** [open-source-economics/Tax-Calculator#1836]
I've hit some snags running through the [contributor guide](http://taxcalc.readthedocs.io/en/latest/contributor_guide.html), starting with the `py.test` step. I'm on Linux and just synced. I don't have the PUF but doesn't look like that should matter here.

```
(taxcalc-dev) mghenis@genghis3:~/github/tax-calculator/taxcalc$ py.test -m "not requires_pufcsv" -n4
============================= test session starts ==============================
platform linux -- Python 3.6.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /usr/local/google/home/mghenis/github/tax-calculator, inifile: setup.cfg
plugins: xdist-1.20.1, forked-0.2, hypothesis-3.38.5, pep8-1.0.6
gw0 [314] / gw1 [314] / gw2 [314] / gw3 [314]
scheduling tests via LoadScheduling
........................................F............................... [ 22%]
...................................................................F.... [ 45%]
........................................................................ [ 68%]
........................................................................ [ 91%]
..........................                                               [100%]
=================================== FAILURES ===================================
__________________________ test_docs_index_up_to_date __________________________
[gw0] linux -- Python 3.6.4 /usr/local/google/home/mghenis/miniconda2/envs/taxcalc-dev/bin/python

tests_path = '/usr/local/google/home/mghenis/github/tax-calculator/taxcalc/tests'

    @pytest.mark.local_test
    def test_docs_index_up_to_date(tests_path):
        """
        Check that index.html timestamp is greater than the timestamp
        of each of its dependencies, where a timestamp is the time a file
        was last modified.
        """
        code_path = os.path.join(tests_path, '..')
        docs_path = os.path.join(code_path, '..', 'docs')
        target = os.path.join(docs_path, 'index.html')
        dependencies = [os.path.join(docs_path, 'index.htmx'),
                        os.path.join(docs_path, 'make_index.py'),
                        os.path.join(code_path, 'current_law_policy.json'),
                        os.path.join(code_path, 'consumption.json'),
                        os.path.join(code_path, 'behavior.json'),
                        os.path.join(code_path, 'growdiff.json'),
                        os.path.join(code_path, 'records_variables.json')]
        target_timestamp = os.path.getmtime(target)
        target_up_to_date = True
        for dep in dependencies:
            if os.path.getmtime(dep) > target_timestamp:
                target_up_to_date = False
        if not target_up_to_date:
            msg = 'Tax-Calculator/docs/index.html IS NOT UP-TO-DATE\n'
            msg += 'FIX BY DOING THIS:                             \n'
            msg += ' $ cd Tax-Calculator/docs                      \n'
            msg += ' $ python make_index.py                        \n'
            msg += 'AND INCLUDE UPDATED index.html IN NEXT COMMIT  \n'
>           raise ValueError(msg)
E           ValueError: Tax-Calculator/docs/index.html IS NOT UP-TO-DATE
E           FIX BY DOING THIS:                             
E            $ cd Tax-Calculator/docs                      
E            $ python make_index.py                        
E           AND INCLUDE UPDATED index.html IN NEXT COMMIT

tests/test_docs.py:41: ValueError
_______________ test_json_file_contents[current_law_policy.json] _______________
[gw3] linux -- Python 3.6.4 /usr/local/google/home/mghenis/miniconda2/envs/taxcalc-dev/bin/python

tests_path = '/usr/local/google/home/mghenis/github/tax-calculator/taxcalc/tests'
fname = 'current_law_policy.json'

    @pytest.mark.parametrize("fname",
                             [("behavior.json"),
                              ("consumption.json"),
                              ("current_law_policy.json"),
                              ("growdiff.json")])
    def test_json_file_contents(tests_path, fname):
        """
        Check contents of JSON parameter files.
        """
        # pylint: disable=too-many-locals,too-many-branches,too-many-statements
        # specify test information
        reqkeys = ['long_name', 'description',
                   'section_1', 'section_2', 'notes',
                   'row_var', 'row_label',
                   'start_year', 'cpi_inflated',
                   'col_var', 'col_label',
                   'value']
        first_year = Policy.JSON_START_YEAR
        last_known_year = Policy.LAST_KNOWN_YEAR  # for indexed parameter values
        num_known_years = last_known_year - first_year + 1
        # read JSON parameter file into a dictionary
        path = os.path.join(tests_path, '..', fname)
        pfile = open(path, 'r')
        allparams = json.load(pfile)
        pfile.close()
        assert isinstance(allparams, dict)
        # check elements in each parameter sub-dictionary
        for pname in allparams:
            param = allparams[pname]
            assert isinstance(param, dict)
            # check that param contains required keys
            for key in reqkeys:
>               assert key in param
E               AssertionError: assert 'notes' in {'boolean_value': False, 'col_label': ['single', 'joint', 'separate', 'headhousehold', 'widow'], 'col_var': 'MARS', 'cpi_inflated': False, ...}

tests/test_parameters.py:82: AssertionError
```

Per the error text, I went to `tax-calculator/docs` to run `make_index.py`, but got this error:

```
(taxcalc-dev) mghenis@genghis3:~/github/tax-calculator/docs$ python make_index.py
Traceback (most recent call last):
  File "make_index.py", line 255, in <module>
    sys.exit(main())
  File "make_index.py", line 49, in main
    text = policy_params(POLICY_PATH, text)
  File "make_index.py", line 158, in policy_params
    ptext += policy_param_text(pname, param)
  File "make_index.py", line 82, in policy_param_text
    if len(param['notes']) > 0:
KeyError: 'notes'
```

**Comment by MaxGhenis** [comment]
Actually I just realized I'm not synced, investigating...

**Comment by martinholmer** [comment]
@MaxGhenis,  The testing procedures have changed.
 Since you don't have `puf.csv`, you should be doing:
```
py.test -m "not requires_pufcsv and not pre_release" -n4
```
Please read the new version of [TESTING.md](https://github.com/open-source-economics/Tax-Calculator/blob/master/TESTING.md) for details.

The current version of the Contributor Guide also specifies the above `py.test` command.

This change was mandated by @MattHJensen, so please follow the new procedures when making a contribution to Tax-Calculator.

**Comment by martinholmer** [comment]
Closing this issue because problems were caused simply by not following the new testing procedures.

**Comment by MaxGhenis** [comment]
Thanks @martinholmer, yes I just had a stale browser tab, sorry for the false alarm.

**Comment by martinholmer** [comment]
@MaxGhenis said:
>  I just had a stale browser tab, all works correctly with the new command. Sorry for the false alarm.

Not problem.  I've been fooled many times by my browser's caching of previously visited web pages.
Sometimes I think modern browsers are too clever by a half.
