### ISSUE TITLE
Need help understanding error message

### ISSUE THREAD

**Issue by martinholmer** [open-source-economics/Tax-Calculator#467]
I'm sure I'm doing something very wrong, but I can't figure out what it is because of the complexity of the following error traceback that seems to be generated from the decorator magic portion of the Tax-Calculator logic.  Any help in explaining the nature of the error would be appreciated.  If I understood what the error message is saying, I might be able to correct my mistake.
```
iMac2:tax-calculator mrh$ python inctax.py ../tax-calculator-data/puf.csv 2013
Traceback (most recent call last):
  File "inctax.py", line 75, in <module>
    sys.exit(main())
  File "inctax.py", line 68, in main
    inctax.calculate()
  File "/Users/mrh/work/OSPC/tax-calculator/taxcalc/incometaxio.py", line 119, in calculate
    self._calc.calc_all()
  File "/Users/mrh/work/OSPC/tax-calculator/taxcalc/calculate.py", line 159, in calc_all
    self.calc_one_year()
  File "/Users/mrh/work/OSPC/tax-calculator/taxcalc/calculate.py", line 114, in calc_one_year
    self.TaxInc_to_AMTI()
  File "/Users/mrh/work/OSPC/tax-calculator/taxcalc/calculate.py", line 94, in TaxInc_to_AMTI
    AMTI(self.policy, self.records)
  File "/Users/mrh/work/OSPC/tax-calculator/taxcalc/decorators.py", line 355, in wrapper
    ans = high_level_fn(*args, **kwargs)
  File "<string>", line 6, in hl_func
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 171, in _compile_for_args
    return self.compile(sig)
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 348, in compile
    flags=flags, locals=self.locals)
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 637, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 358, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 367, in compile_bytecode
    return self._compile_bytecode()
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 624, in _compile_bytecode
    return pm.run(self.status)
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 250, in run
    raise patched_exception
numba.errors.TypingError: Caused By:
Traceback (most recent call last):
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 242, in run
    res = stage()
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 455, in stage_nopython_frontend
    self.locals)
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 752, in type_inference_stage
    infer.propagate()
  File "/Users/mrh/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 510, in propagate
    raise errors[0]
TypingError: Invalid usage of getitem with parameters (int64, int64)
 * parameterized
File "<string>", line 3

Failed at nopython (nopython frontend)
Invalid usage of getitem with parameters (int64, int64)
 * parameterized
File "<string>", line 3
iMac2:tax-calculator mrh$ 
```
cc T.J. @talumbau 
P.S. I'm trying to calculate income taxes for 2013 for the filing units in the puf.csv file dated 10-Oct-2015.
@Amy-Xu ,  Is there a more recent version of puf.csv that I should be using?

**Comment by Amy-Xu** [comment]
@martinholmer where's the inctax.py script you ran here? I couldn't find it from my local files. But purely a random guess from the error message here: it might be a data type related issue for the variables used in AMTI function. The variables imported from your puf might not be integers.

**Comment by martinholmer** [comment]
@Amy-Xu said:
> where's the inctax.py script you ran here? I couldn't find it from my local files.

Thanks for the quick response.  The script has not been merged into the master branch, but you can see it on my inctax0 branch (in the Network Graph on Git Hub).

I tried to read in a puf.csv file that has a 10-Oct-2015 date.  Should I be using a newer version of puf.csv?

**Comment by Amy-Xu** [comment]
I'm not quite sure which version of puf it is. Do you always use that file to set up a regular calculator?

**Comment by martinholmer** [comment]
@Amy-Xu said:
> I'm not quite sure which version of puf it is. Do you always use that file to set up a regular calculator?

I rarely, if ever, "set up a regular calculator".  Just to be sure I'm using the current puf.csv, can you point me (in private email) to a link with the current OSPC version of puf.csv?

**Comment by MattHJensen** [comment]
fyi, I cloned @martinholmer's inctax0 branch locally and just ran inctax.py with no errors: 

```
(taxcalc-dev)Matt-Jensens-MacBook-Pro:tax-calculator Matt.Jensen$ python inctax.py /Users/matt.jensen/proj/tax-calculator/puf.csv 2013
You loaded data for 2009.
Your data have been extrapolated to 2013.
(taxcalc-dev)Matt-Jensens-MacBook-Pro:tax-calculator Matt.Jensen$
```

I used the cps-matched file: (129,682,845 bytes (129.7 MB on disk))

I am using the taxcalc-dev conda env as prescribed in the contributor guide:

```
apipkg                    1.4                       <pip>
appnope                   0.1.0                    py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
certifi                   14.05.14                 py27_0  
decorator                 4.0.4                    py27_0  
enum34                    1.0.4                    py27_0  
execnet                   1.4.1                     <pip>
freetype                  2.5.2                         2  
funcsigs                  0.4                      py27_0  
ipykernel                 4.1.0                    py27_0  
ipython                   4.0.0                    py27_1  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_0  
ipython_genutils          0.1.0                    py27_0  
jinja2                    2.8                      py27_0  
jsonschema                2.4.0                    py27_0  
jupyter-client            4.1.1                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py27_0  
jupyter_core              4.0.6                    py27_0  
libpng                    1.6.17                        0  
libsodium                 0.4.5                         0  
llvmlite                  0.7.0                    py27_3  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_3  
mistune                   0.7.1                    py27_0  
nbconvert                 4.0.0                    py27_0  
nbformat                  4.0.1                    py27_0  
notebook                  4.0.6                    py27_0  
numba                     0.21.0               np19py27_0  
numpy                     1.9.3                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.1               np19py27_0  
path.py                   8.1.2                    py27_0  
pep8                      1.6.2                     <pip>
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pip                       7.1.2                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.30                   py27_0  
pygments                  2.0.2                    py27_0  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.4                   py27_0  
pytest                    2.8.1                    py27_0  
pytest-cache              1.0                       <pip>
pytest-pep8               1.0.6                     <pip>
python                    2.7.10                        1  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.6                   py27_0  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.7                         1  
readline                  6.2                           2  
setuptools                18.4                     py27_0  
simplegeneric             0.8.1                    py27_0  
singledispatch            3.4.0.3                  py27_0  
sip                       4.16.9                   py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.4                    py27_0  
tornado                   4.2.1                    py27_0  
traitlets                 4.0.0                    py27_0  
wheel                     0.26.0                   py27_1  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by martinholmer** [comment]
@MattHJensen said:
> I cloned @martinholmer's inctax0 branch locally and just ran inctax.py with no errors.

That is because you used an inctax0 check-in that had been modified to avoid the decorator crash.

**Comment by martinholmer** [comment]
I finally found my error (without any help from the Python error traceback).  I'm closing this issue.
